# Generated by Django 3.0.2 on 2020-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='topic',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
